packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: ^5.7.2
  vitest: ^2.1.8
  zod: ^3.24.1

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
